[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
pump_fun = "BDmyUtXfoCXubpBTscdVFRGrvu6RN6geGTSypRm4BbwQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

# Remove the genesis configuration as it's not needed
# The SPL token program is already deployed on localnet
